<?php

namespace AppBundle\Repository;

/**
 * CableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CableRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommandeCablesPalettes($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT p
              FROM AppBundle:Palette p
              INNER JOIN AppBundle:commandeCable cc WITH cc.commande =:id AND cc.cable = p.cable")
            ->setParameter('id', $id);

        return $query->getResult();
    }

    public function getCommandeCablesTourets($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT t
              FROM AppBundle:Touret t
              INNER JOIN AppBundle:commandeCable cc WITH cc.commande =:id AND cc.cable = t.cable")
            ->setParameter('id', $id);

        return $query->getResult();
    }
}
