<?php

namespace AppBundle\Repository;

/**
 * CableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CableRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommandeCables($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c as cable, count(p) as palettes, count(t) as tourets
              FROM AppBundle:Cable c
              INNER JOIN c.cableCommande cc WITH cc.commande =:id
              LEFT JOIN AppBundle:Palette p WITH p.cable = c
              LEFT JOIN AppBundle:Touret t WITH t.cable = c")
            ->setParameter('id', $id);

        return $query->getResult();
    }
}
