<?php

namespace AppBundle\Repository;

/**
 * CommandeCableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeCableRepository extends \Doctrine\ORM\EntityRepository
{
    public function DetailsCommande($id)
    {
        $query = $this->getEntityManager()->createQuery("SELECT cc FROM AppBundle:CommandeCable cc WHERE cc.commande =:id")
            ->setParameter('id', $id);

        return $query->getResult();
    }
}
