<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommandesOuvrier($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM AppBundle:Commande c WHERE c.ouvrier =:id")
            ->setParameter('id', $id);

        return $query->getResult();
    }
}
