<?php

namespace AppBundle\Repository;

/**
 * PaletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaletteRepository extends \Doctrine\ORM\EntityRepository
{
}
