<?php

namespace AppBundle\Repository;

/**
 * TouretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouretRepository extends \Doctrine\ORM\EntityRepository
{
}
